### ISSUE TITLE
Throwing exception on startup

### ISSUE THREAD

**Issue by cs96and** [EthanJWright/foundryvtt-importer#50]
**Describe the bug**
Content Parser is throwing an exception on startup

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/data/Data/modules/foundry-vtt-content-parser/templates/importForm.hbs'
[Detected 1 package: foundry-vtt-content-parser]
    at o.<anonymous> (foundry.js:4656:40)
    at o.value (socket.js:307:17)
    at o.value (socket.js:237:22)
    at T.emit (index.js:143:20)
    at s.value (manager.js:200:14)
    at T.emit (index.js:143:20)
    at a.value (index.js:105:51)
    at s.value (manager.js:192:22)
    at T.emit (index.js:143:20)
    at a.value (socket.js:323:26)
    at T.emit (index.js:143:20)
    at o.value (transport.js:99:14)
    at o.value (transport.js:92:14)
    at ws.onmessage (websocket.js:76:40)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/898086/173675677-30bf91f2-97ce-4efd-9202-75e161aebdae.png)

**Comment by EthanJWright** [comment]
Good catch - issue was in a template rendered that isn't tested well and wasn't throwing errors on build.

Should be good now!
